categories:
  - name: Admin Tools
    icon: ''
  - name: Essentials
    icon: ''
  - name: Security
    icon: ''
  - name: Gameplay
    icon: ''
  - name: Fun
    icon: ''
  - name: SCP
    icon: ''
  - name: Humans
    icon: ''
  - name: Commands
    icon: ''
